//TODO: move this somewhere else its so ugly
opcode opcodes[] = {
  //0x00
  {NULL, "brk", NULL},
  {OP_ora, "ora", addr_zp_idx_indirect},
  {OP_nop, "nop1", addr_implied},
  {NULL, "slo", NULL},
  {OP_nop, "nop2", addr_implied},
  {OP_ora, "ora", addr_zp},
  {OP_asl, "asl", addr_zp},
  {NULL, "slo", NULL},
  {OP_php, "php", addr_stack},
  {OP_ora, "ora", addr_imm},
  {OP_aslA, "asl", addr_accumulator},
  {OP_nop, "nop3", addr_implied},
  {OP_nop, "nop4", addr_implied},
  {OP_ora, "ora", addr_abs},
  {OP_asl, "asl", addr_abs},
  {NULL, "slo", NULL},

  //0x10
  {OP_bpl, "bpl", addr_pcr},
  {OP_ora, "ora", addr_zp_idx_y_indirect},
  {OP_ora, "ora", addr_zp_indirect},
  {NULL, "slo", NULL},
  {OP_nop, "nop6", addr_implied},
  {OP_ora, "ora", addr_zp_idx_x},
  {OP_asl, "asl", addr_zp_idx_x},
  {NULL, "slo", NULL},
  {OP_clc, "clc", addr_implied},
  {OP_ora, "ora", addr_abs_y},
  {OP_inc, "inc", addr_accumulator},
  {NULL, "slo", NULL},
  {OP_nop, "nop8", addr_implied},
  {OP_ora, "ora", addr_abs_x},
  {OP_asl, "asl", addr_abs_x},
  {NULL, "slo", NULL},

  //0x20
  {OP_jsr, "jsr", addr_abs},
  {OP_and, "and", addr_zp_idx_indirect},
  {OP_nop, "nop9", addr_implied},
  {NULL, "rla", NULL},
  {OP_bit, "bit", addr_zp},
  {OP_and, "and", addr_zp},
  {OP_rol, "rol", addr_zp},
  {NULL, "rla", NULL},
  {OP_plp, "plp", addr_stack},
  {OP_and, "and", addr_imm},
  {OP_rolA, "rol", addr_accumulator},
  {OP_nop, "nop10", addr_implied},
  {OP_bit, "bit", addr_abs},
  {OP_and, "and", addr_abs},
  {OP_rol, "rol", addr_abs},
  {NULL, "rla", NULL},

  //0x30
  {OP_bmi, "bmi", addr_pcr},
  {OP_and, "and", addr_zp_idx_y},
  {OP_and, "and", addr_zp_indirect},
  {NULL, "rla", NULL},
  {OP_bit, "bit", addr_zp_idx_x},
  {OP_and, "and", addr_zp_idx_x},
  {OP_rol, "rol", addr_zp_idx_x},
  {NULL, "rla", NULL},
  {OP_sec, "sec", addr_implied},
  {OP_and, "and", addr_abs_y},
  {OP_dec, "dec", addr_accumulator},
  {NULL, "rla", NULL},
  {OP_bit, "bit", addr_abs_x},
  {OP_and, "and", addr_abs_x},
  {OP_rol, "rol", addr_abs_x},
  {NULL, "rla", NULL},

  //0x40
  {NULL, "rti", NULL},
  {OP_eor, "eor", addr_zp_indirect},
  {OP_nop, "nop15", addr_implied},
  {NULL, "sre", NULL},
  {OP_nop, "nop16", addr_implied},
  {OP_eor, "eor", addr_zp},
  {OP_lsr, "lsr", addr_zp},
  {NULL, "sre", NULL},
  {OP_pha, "pha", addr_stack},
  {OP_eor, "eor", addr_imm},
  {OP_lsrA, "lsr", addr_accumulator},
  {OP_nop, "nop17", addr_implied},
  {OP_jmp, "jmp", addr_abs},
  {OP_eor, "eor", addr_abs},
  {OP_lsr, "lsr", addr_abs},
  {NULL, "sre", NULL},

  //0x50
  {NULL, "bvc", NULL},
  {OP_eor, "eor", addr_zp_idx_y_indirect},
  {OP_nop, "nop18", addr_implied},
  {NULL, "sre", NULL},
  {OP_nop, "nop19", addr_implied},
  {OP_eor, "eor", addr_zp_idx_x},
  {OP_lsr, "lsr", addr_zp_idx_x},
  {NULL, "sre", NULL},
  {NULL, "cli", NULL},
  {OP_eor, "eor", addr_abs_y},
  {OP_phx, "phx", addr_stack},
  {NULL, "sre", NULL},
  {OP_nop, "nop21", addr_implied},
  {OP_eor, "eor", addr_abs_x},
  {OP_lsr, "lsr", addr_abs_x},
  {NULL, "sre", NULL},

  //0x60
  {OP_rts, "rts", addr_stack},
  {OP_adc, "adc", addr_zp_idx_indirect},
  {OP_nop, "nop22", addr_implied},
  {NULL, "rra", NULL},
  {OP_stz, "stz", addr_zp},
  {OP_adc, "adc", addr_zp},
  {OP_ror, "ror", addr_zp},
  {NULL, "rra", NULL},
  {NULL, "pla", NULL},
  {OP_adc, "adc", addr_imm},
  {OP_rorA, "ror", addr_accumulator},
  {OP_nop, "nop24", addr_implied},
  {OP_jmp, "jmp", addr_abs_indirect},
  {OP_adc, "adc", addr_abs},
  {OP_ror, "ror", addr_abs},
  {NULL, "rra", NULL},

  //0x70
  {OP_bvs, "bvs", addr_pcr},
  {OP_adc, "adc", addr_zp_idx_y_indirect},
  {OP_adc, "adc", addr_zp_indirect},
  {NULL, "rra", NULL},
  {OP_stz, "stz", addr_zp_idx_x},
  {OP_adc, "adc", addr_zp_idx_x},
  {OP_ror, "ror", addr_zp_idx_x},
  {NULL, "rra", NULL},
  {OP_sei, "sei", addr_implied},
  {OP_adc, "adc", addr_abs_y},
  {OP_ply, "ply", addr_stack},
  {NULL, "rra", NULL},
  {OP_jmp, "jmp", addr_abs_idx_indirect},
  {OP_adc, "adc", addr_abs_x},
  {OP_ror, "ror", addr_abs_x},
  {NULL, "rra", NULL},

  //0x80
  {OP_bra, "bra", addr_pcr},
  {OP_sta, "sta", addr_zp_idx_indirect},
  {OP_nop, "nop29", addr_implied},
  {NULL, "sax", NULL},
  {OP_sty, "sty", addr_zp},
  {OP_sta, "sta", addr_zp},
  {OP_stx, "stx", addr_zp},
  {NULL, "sax", NULL},
  {OP_dey, "dey", addr_implied},
  {OP_bit, "bit", addr_imm},
  {NULL, "txa", NULL},
  {OP_nop, "nop31", addr_implied},
  {OP_sty, "sty", addr_abs},
  {OP_sta, "sta", addr_abs},
  {OP_stx, "stx", addr_abs},
  {NULL, "sax", NULL},

  //0x90
  {OP_bcc, "bcc", addr_pcr},
  {OP_sta, "sta", addr_zp_idx_y_indirect},
  {OP_sta, "sta", addr_zp_indirect},
  {OP_nop, "nop33", addr_implied},
  {OP_sty, "sty", addr_zp_idx_x},
  {OP_sta, "sta", addr_zp_idx_x},
  {OP_stx, "stx", addr_zp_idx_y},
  {NULL, "sax", NULL},
  {OP_tya, "tya", addr_implied},
  {OP_sta, "sta", addr_abs_y},
  {NULL, "txs", NULL},
  {OP_nop, "nop34", addr_implied},
  {OP_stz, "stz", addr_abs},
  {OP_sta, "sta", addr_abs_x},
  {OP_stz, "stz", addr_abs_x},
  {OP_nop, "nop37", addr_implied},

  //0xA0
  {OP_ldy, "ldy", addr_imm},
  {OP_lda, "lda", addr_zp_idx_indirect},
  {OP_ldx, "ldx", addr_imm},
  {NULL, "lax", NULL},
  {OP_ldy, "ldy", addr_zp},
  {OP_lda, "lda", addr_zp},
  {OP_ldx, "ldx", addr_zp},
  {NULL, "lax", NULL},
  {OP_tay, "tay", addr_implied},
  {OP_lda, "lda", addr_imm},
  {NULL, "tax", NULL},
  {OP_nop, "nop38", addr_implied},
  {OP_ldy, "ldy", addr_abs},
  {OP_lda, "lda", addr_abs},
  {OP_ldx, "ldx", addr_abs},
  {NULL, "lax5", NULL},

  //0xB0
  {OP_bcs, "bcs", addr_pcr},
  {OP_lda, "lda", addr_zp_idx_y_indirect},
  {OP_lda, "lda", addr_zp_indirect},
  {NULL, "lax2", NULL},
  {OP_ldy, "ldy", addr_zp_idx_x},
  {OP_lda, "lda", addr_zp_idx_x},
  {OP_ldx, "ldx", addr_zp_idx_y},
  {NULL, "lax4", NULL},
  {NULL, "clv", NULL},
  {OP_lda, "lda", addr_abs_y},
  {NULL, "tsx", NULL},
  {NULL, "lax1", NULL},
  {OP_ldy, "ldy", addr_abs_x},
  {OP_lda, "lda", addr_abs_x},
  {OP_ldx, "ldx", addr_abs_y},
  {NULL, "lax3", NULL},

  //0xC0
  {OP_cpy, "cpy", addr_imm},
  {NULL, "cmp", NULL},
  {OP_nop, "nop40", addr_implied},
  {NULL, "dcp", NULL},
  {OP_cpy, "cpy", addr_zp},
  {NULL, "cmp", NULL},
  {OP_dec, "dec", addr_zp},
  {NULL, "dcp", NULL},
  {OP_iny, "iny", addr_implied},
  {NULL, "cmp", NULL},
  {OP_dex, "dex", addr_implied},
  {OP_nop, "nop41", addr_implied},
  {OP_cpy, "cpy", addr_abs},
  {NULL, "cmp", NULL},
  {OP_dec, "dec", addr_abs},
  {NULL, "dcp", NULL},

  //0xD0
  {OP_bne, "bne", addr_pcr},
  {NULL, "cmp", NULL},
  {OP_nop, "nop42", addr_implied},
  {NULL, "dcp", NULL},
  {OP_nop, "nop43", addr_implied},
  {NULL, "cmp", NULL},
  {OP_dec, "dec", addr_zp_idx_x},
  {NULL, "dcp", NULL},
  {NULL, "cld", NULL},
  {NULL, "cmp", NULL},
  {OP_phx, "phx", addr_stack},
  {NULL, "dcp", NULL},
  {OP_nop, "nop45", addr_implied},
  {NULL, "cmp", NULL},
  {OP_dec, "dec", addr_abs_x},
  {NULL, "dcp", NULL},

  //0xE0
  {OP_cpx, "cpx", addr_imm},
  {OP_sbc, "sbc", addr_zp_idx_indirect},
  {OP_nop, "nop46", addr_implied},
  {NULL, "isb", NULL},
  {OP_cpx, "cpx", addr_zp},
  {OP_sbc, "sbc", addr_zp},
  {OP_inc, "inc", addr_zp},
  {NULL, "isb", NULL},
  {OP_inx, "inx", addr_implied},
  {OP_sbc, "sbc", addr_imm},
  {OP_nop, "nop", addr_implied},
  {NULL, "sbc", NULL},
  {OP_cpx, "cpx", addr_abs},
  {OP_sbc, "sbc", addr_abs},
  {OP_inc, "inc", addr_abs},
  {NULL, "isb", NULL},

  //0xF0
  {OP_beq, "beq", addr_pcr},
  {OP_sbc, "sbc", addr_zp_idx_y_indirect},
  {OP_nop, "nop48", addr_implied},
  {NULL, "isb", NULL},
  {OP_nop, "nop49", addr_implied},
  {OP_sbc, "sbc", addr_zp_idx_x},
  {OP_inc, "inc", addr_zp_idx_x},
  {NULL, "isb", NULL},
  {OP_sed, "sed", addr_implied},
  {OP_sbc, "sbc", addr_abs_y},
  {OP_plx, "plx", addr_stack},
  {NULL, "isb", NULL},
  {OP_nop, "nop51", addr_implied},
  {OP_sbc, "sbc", addr_abs_x},
  {OP_inc, "inc", addr_abs_x},
  {NULL, "isb", NULL}
};
