name: Example Binaries

on:
  push:
    branches: [ "main" ]
    paths:
      - "example_bins/**"
  pull_request:
    branches: [ "main" ]
    paths:
      - "example_bins/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: download vasm
      run: wget http://www.ibaug.de/vasm/vasm6502.zip
    - name: unpackaging
      run: unzip vasm6502.zip
    - name: symlinking
      run: ln -s vasm6502_oldstyle/linux/vasm6502_oldstyle vasm
    - name: make
      run: export PATH=$(pwd):$PATH && cd example_bins && make
    
